version: '2'
services:

  owt-server:
    build:
      context: ../
      dockerfile: Dockerfile
      args:
        - http_proxy
        - https_proxy
    image: owt-server
  owt-server-conference:
    build:
      context: .
      dockerfile: Dockerfile-conference
      args:
        - http_proxy
        - https_proxy
    image: owt-server-conference
    ports:
      - "3000:3000"
      - "3001:3001"
      - "3004:3004"
      - "3300:3300"
      - "8080:8080"
    command: sh -c "service mongodb start && service rabbitmq-server start \
                    && cd /owt-server/dist/bin && ./init-all.sh && ./start-all.sh && sleep infinity"
    depends_on:
      - owt-server
